---
kind: pipeline
name: unit-test

steps:

  - name: app-init
    image: registry.dev.wisetime.com/check-frontend
    commands:
      - make clean
      - make init

  - name: lint
    image: registry.dev.wisetime.com/check-frontend
    commands:
      - npm run eslint

  - name: test
    image: registry.dev.wisetime.com/check-frontend
    commands:
      - npm test

trigger:
  event:
    - push
